Chore: NestJS 스켈레톤 프로젝트 초기 설정
pre-onboarding-backend-G/team-g-project-skeleton pull request #2
Opened 2023-10-25 05:40 UTC by Zamoca42

## PR 체크리스트
아래 항목을 확인해 주세요:

- [x] 커밋 메시지가 우리의 가이드라인을 따르고 있는지 확인하세요
- [ ] 변경 사항에 대한 테스트가 추가되었는지 확인하세요 (버그 수정 / 기능 추가)
- [ ] 문서가 추가되거나 업데이트되었는지 확인하세요 (버그 수정 / 기능 추가)

## PR 유형
이 PR은 어떤 종류의 변경을 가져오나요?

- [ ] 버그 수정
- [ ] 새로운 기능 추가
- [ ] 코드 스타일 업데이트 (서식, 로컬 변수)
- [ ] 리팩터링 (기능 변경 없음, API 변경 없음)
- [x] 빌드 관련 변경
- [x] CI 관련 변경
- [x] 문서 내용 변경
- [x] 애플리케이션 / 인프라 변경
- [ ] 기타... 설명:

## 현재 동작은 무엇인가요?

이슈 번호: #1 

## 새로운 동작은 무엇인가요?

## 이 PR은 호환성 변경을 도입하나요?

- [ ] 예
- [x] 아니요

## 기타 정보

2023-10-25 14:32 UTC, myeongseoklee requested changes
몇 가지 제안과 수정 요청을 남겼습니다. 오늘 고생 많으셨습니다!

2023-10-25 14:32 UTC, myeongseoklee commented on .gitignore
> +!.vscode/extensions.json
env 파일도 추가되어야 할 것 같습니다!

2023-10-25 14:32 UTC, myeongseoklee commented on package.json
> +  },
```suggestion
{"packageManager": "yarn@1.22.19",
	"engines": {
		"node": "18.16.1"
	},
```

제가 전에 개인프로젝트 할 때 노드버전과 패키지매니저 버전을 고정하려고 사용했었는데요.
버전 안정성을 위해 노드 버전을 명확히 지정하거나, 몇 버전 이상의 버전을 사용해야 한다는 등 규칙을 적을 수 있습니다.
docker 이미지가 돌아가는 환경의 노드버전과 일치시키면 어떨까 싶습니다.(가능하다면 패키지 매니저버전까지)

저같은 경우는 node 18.16 버전을 사용중인데, docker에 설정하신 노드버전을 보면 20이더라구요.
다른 분들도 노드버전이 다르시지 않을까 싶어, 명시해두면 좋을 것 같아 제안드립니다.

참고로 로컬에서 node 버전은 매번 바꿔주기 귀찮을 수 있으니 프로젝트의 루트에 .nvmrc 파일 추가하고 몇 가지 쉘 스크립트를 작성하면 패키지별로 지정한 노드버전이 다르더라도 해당 버전으로 작업이 됩니다.
(참고: https://hyeok999.github.io/2020/06/02/NVM/#a5)

2023-10-25 14:32 UTC, myeongseoklee commented on docker/local.Dockerfile
> +RUN npm install
```suggestion
Run npm ci
```
"npm i"는 실행 시, package.json에 ^ 또는 ~를 사용하는 경우 지정된 버전과 동일한 버전을 설치하지 못할 수 있다고 합니다.
따라서, 버전이 달라지면 package-lock.json이 업데이트 되므로 새로운 의존성을 설치할 때가 아니라
1. CI/CD 과정에서 전체 의존성을 설치 하거나
2. 프로젝트 레포지토리를 처음 clone 받아 의존성을 설치할 때는
"npm ci"를 사용하는 것이 좋다고 합니다.
(참고: https://doqtqu.tistory.com/353)

2023-10-25 14:32 UTC, myeongseoklee commented on .github/workflows/ci.yml
> +      - 'develop'
저희 develop 브랜치가 없어서 삭제해도 될 것 같습니다.

2023-10-25 14:32 UTC, myeongseoklee commented on package.json
> +    "start:dev": "cross-env NODE_ENV=development nest start",
저희 개발서버가 따로 없어서, dev env 주입해서 서버를 킬 일이 있을까 싶어요!

2023-10-25 14:32 UTC, myeongseoklee commented on src/common/env.validation.ts
> +}
Q. env에서 사용할 필드를 class의 멤버변수로 추가해주어야 하나요?

DYNAMODB_TABLE_PREFIX 멤버변수는 필요한 값이 아니면 삭제해야 할 것 같습니다.

2023-10-25 14:32 UTC, myeongseoklee commented on src/common/filter/http-exception.filter.ts
> +    }
여기서 BadRequestException인 경우만 따로 처리하신 이유가 있을까요?

2023-10-25 14:32 UTC, myeongseoklee commented on src/main.ts
> +
```suggestion
  app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));
```
위 코드를 혹시 추가해주실 수 있을까요? 응답객체 직렬화에 사용합니다.
(참고: https://jojoldu.tistory.com/610)

2023-10-25 16:19 UTC, Zamoca42 commented on src/main.ts
> +
네 참고링크가 많은 도움되었습니다! 이 부분도 추가해보겠습니다

2023-10-25 16:20 UTC, Zamoca42 commented on src/common/filter/http-exception.filter.ts
> +    }
저번 프로젝트에서 그대로 exception filter를 가져와봤는데, 저번 프로젝트에서는 프론트에서 400error를 직접 보내는일이 많아서 저렇게 처리해줬었던걸로 기억합니다. 일반화할 때는 필요없는 부분인거 같아서 이번에는 제외하겠습니다.

2023-10-25 16:22 UTC, Zamoca42 commented on package.json
> +    "start:dev": "cross-env NODE_ENV=development nest start",
요것도 예시상황으로 넣어봤는데 환경부분 검증에서 제외할 필요가 있겠네요

2023-10-25 16:22 UTC, Zamoca42 commented on .github/workflows/ci.yml
> +      - 'develop'
넵 회의시간에 논의했던 부분이라 제외하겠습니다.

2023-10-25 16:23 UTC, Zamoca42 commented on docker/local.Dockerfile
> +RUN npm install
npm install -> ci로 변경했습니다

2023-10-25 16:49 UTC, Zamoca42 commented on package.json
> +  },
> 저같은 경우는 node 18.16 버전을 사용중인데, docker에 설정하신 노드버전을 보면 20이더라구요.
> 다른 분들도 노드버전이 다르시지 않을까 싶어, 명시해두면 좋을 것 같아 제안드립니다.

이 부분에서 제 의도와는 다른거 같아서 코멘트 남깁니다. 제가 docker compose를 사용한 부분은 로컬 환경에서 노드 버전이 모두 다르기 때문에 `docker compose up`을 사용하게 되면 node 20 버전으로 도커 환경 실행되니까 모두 같은 노드 버전의 환경에서 작업해볼 수 있기 때문에 도커를 사용했는데요.
로컬에서까지 노드 버전을 맞춰서 작업하게되면 도커 컴포즈가 의미가 없게 되는거 같습니다.

2023-10-25 17:02 UTC, Zamoca42 commented on docker/local.Dockerfile
> +RUN npm install
네 이부분은 npm install -> ci로 변경해보겠습니다

2023-10-25 17:05 UTC, Zamoca42 commented on package.json
> +    "start:dev": "cross-env NODE_ENV=development nest start",
dev env를 제외하고 env.example로 환경 변수 예시를 추가했습니다.

2023-10-25 17:10 UTC, myeongseoklee commented on package.json
> +  },
아 네넵 그부분은 이해했습니다.

그럼 도커 컨테이너 위에서 의존성 패키지를 npm install 하게되면 도커 컨테이너의 node version에 맞게 의존성 버전이 제대로 설치된다는 말씀이시죠?

저는 그 부분까지는 몰랐고, 도커를 사용하지 않으면 npm install은 로컬의 node version을 따라가니까 일치해야하지 않나 생각했었어요😅

그렇다면, "꼭" 도커 컨테이너를 띄우고 작업해야겠군요!

2023-10-25 17:21 UTC, myeongseoklee commented on src/common/filter/http-exception.filter.ts
> +    }
```suggestion
switch (exception.constructor) {
      case HttpException: // for HttpException
        status = (exception as HttpException).getStatus();
        break;

      case QueryFailedError: // for TypeOrm error
        status = HttpStatus.UNPROCESSABLE_ENTITY;
        message = (exception as QueryFailedError).message;
        code = (exception as any).code;
        break;

      case BadRequestException:
        status = (exception as BadRequestException).getStatus();
        break;

      case UnauthorizedException: // for Auth guard error
        status = (exception as UnauthorizedException).getStatus();
        break;

      case ForbiddenException:
        status = (exception as ForbiddenException).getStatus();
        break;

      case NotFoundException:
        status = (exception as NotFoundException).getStatus();
        break;

      case ConflictException:
        status = (exception as ConflictException).getStatus();
        break;

      default: // default
        status = HttpStatus.INTERNAL_SERVER_ERROR;
    }
```

ㅋㅋ 저도 실은 전 프로젝트에서 exception filter에 에러별로 status 할당하는 메소드를 사용하긴 했었는데요, 이번에 다시 보니 BadRequestException 등 여러 exception의 부모 클래스가 HttpException이더라구요. 그래서 사실상 제가 만들어 썼던 메소드가 큰 의미가 없었다는 것을 깨닫게 되어서, 혹시 연규님은 다른 의도가 있나 궁금해서 여쭤봤습니다!

2023-10-25 17:27 UTC, Zamoca42 commented on src/main.ts
> +
main.ts에서 글로벌 인터셉터를 추가했습니다

2023-10-25 17:28 UTC, Zamoca42 commented on src/common/filter/http-exception.filter.ts
> +    }
exception filter에서 BadRequest(400)만 따로 처리하는 경우를 제외했습니다

2023-10-25 17:28 UTC, Zamoca42 commented on .github/workflows/ci.yml
> +      - 'develop'
ci에서 develop 브랜치를 제외하고 feature 브랜치만 명시했습니다

2023-10-26 00:55 UTC, hojoonSong commented
node환경이 오랜만이고, docker compose와 각종 의존성들을 미리 합의하는 과정 잘 보고 배웠습니다!

2023-10-26 01:23 UTC, myeongseoklee approved these changes

2023-10-26 02:12 UTC, refigo approved these changes
초기 설정 확인했습니다!

2023-10-26 02:31 UTC, hojoonSong approved these changes

2023-10-26 02:31 UTC, Sangun-Lee-6 approved these changes

2023-10-26 02:32 UTC, merged